# Copyright 2017 Tymoteusz Oleniecki
#
# This file is part of PyDesc.
#
# PyDesc is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# PyDesc is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with PyDesc.  If not, see <http://www.gnu.org/licenses/>.

"""Classes representing building blocks of structures: mer and compounds."""

from pydesc.config import ConfigManager

# pylint: disable=no-member
ConfigManager.new_branch("chemistry")
ConfigManager.chemistry.set_default("backbone_atoms", ())
ConfigManager.chemistry.set_default("bb_bond_threshold", 2.0)
ConfigManager.chemistry.set_default("solvent", ["HOH"])
ConfigManager.chemistry.set_default("moving_average", 3)
ConfigManager.chemistry.new_branch("mer")
ConfigManager.chemistry.mer.set_default("check_distances", False)
ConfigManager.chemistry.mer.set_default(
    "code",
    {
        "ILE": "I",
        "GLN": "Q",
        "GLX": "Z",
        "GLY": "G",
        "GLU": "E",
        "CYS": "C",
        "HIS": "H",
        "SER": "S",
        "LYS": "K",
        "PRO": "P",
        "ASX": "B",
        "ASN": "N",
        "VAL": "V",
        "THR": "T",
        "ASP": "D",
        "TRP": "W",
        "PHE": "F",
        "ALA": "A",
        "MET": "M",
        "LEU": "L",
        "ARG": "R",
        "TYR": "Y",
        "G": "G",
        "C": "C",
        "U": "U",
        "A": "A",
        "DG": "G",
        "DA": "A",
        "DT": "T",
        "DC": "C",
    },
)
ConfigManager.chemistry.mer.set_default(
    "additional_code",
    {
        "DNP": "A",
        "ABI": "A",
        "ALM": "A",
        "MAA": "A",
        "TIH": "A",
        "FLA": "A",
        "DAL": "A",
        "CSD": "A",
        "BNN": "A",
        "HAC": "A",
        "PRR": "A",
        "AYA": "A",
        "CHG": "A",
        "DHA": "A",
        "TPQ": "A",
        "SEG": "A",
        "DIV": "V",
        "MVA": "V",
        "DVA": "V",
        "BUG": "L",
        "DLE": "L",
        "CLE": "L",
        "NLN": "L",
        "NLE": "L",
        "NLP": "L",
        "MLE": "L",
        "LEF": "L",
        "DIL": "I",
        "IIL": "I",
        "DPR": "P",
        "HYP": "P",
        "MSE": "M",
        "OMT": "M",
        "CXM": "M",
        "FME": "M",
        "MME": "M",
        "DAH": "F",
        "PHI": "F",
        "DPN": "F",
        "HPQ": "F",
        "PHL": "F",
        "LTR": "W",
        "TPL": "W",
        "DTR": "W",
        "TRO": "W",
        "HTR": "W",
        "MSA": "G",
        "SAR": "G",
        "MPQ": "G",
        "GLZ": "G",
        "GSC": "G",
        "GL3": "G",
        "NMC": "G",
        "DSN": "S",
        "SEL": "S",
        "SEP": "S",
        "SET": "S",
        "SAC": "S",
        "SVA": "S",
        "MIS": "S",
        "OAS": "S",
        "TPO": "T",
        "ALO": "T",
        "DTH": "T",
        "BMT": "T",
        "BCS": "C",
        "SOC": "C",
        "C5C": "C",
        "C6C": "C",
        "SCS": "C",
        "PEC": "C",
        "DCY": "C",
        "EFC": "C",
        "SCY": "C",
        "SMC": "C",
        "CSX": "C",
        "BUC": "C",
        "CSO": "C",
        "PR3": "C",
        "CCS": "C",
        "CEA": "C",
        "CME": "C",
        "CSP": "C",
        "CSS": "C",
        "CSW": "C",
        "CY1": "C",
        "CY3": "C",
        "CYG": "C",
        "CYM": "C",
        "CYQ": "C",
        "SCH": "C",
        "SHC": "C",
        "OCS": "C",
        "CAS": "C",
        "TYQ": "Y",
        "TYS": "Y",
        "TYB": "Y",
        "STY": "Y",
        "DTY": "Y",
        "IYR": "Y",
        "PAQ": "Y",
        "TYY": "Y",
        "PTR": "Y",
        "TYI": "Y",
        "MEN": "N",
        "DGN": "Q",
        "MGN": "Q",
        "2AS": "D",
        "ASB": "D",
        "DAS": "D",
        "ASK": "D",
        "ASL": "D",
        "ASQ": "D",
        "BHD": "D",
        "ASA": "D",
        "DSP": "D",
        "5HP": "E",
        "CGU": "E",
        "DGL": "E",
        "GMA": "E",
        "GGL": "E",
        "PCA": "E",
        "DLY": "K",
        "LYM": "K",
        "LLY": "K",
        "LYZ": "K",
        "KCX": "K",
        "LLP": "K",
        "TRG": "K",
        "SHR": "K",
        "ALY": "K",
        "ARM": "R",
        "ACL": "R",
        "HAR": "R",
        "HMR": "R",
        "AGM": "R",
        "DAR": "R",
        "HIC": "H",
        "3AH": "H",
        "NEM": "H",
        "NEP": "H",
        "DHI": "H",
        "MHS": "H",
        "HIP": "H",
    },
)

ConfigManager.new_branch("structure_mon")
ConfigManager.structure_mon.set_default(
    "simple_secondary_structure_code",
    {
        "H": "H",
        "B": "E",
        "E": "E",
        "G": "H",
        "I": "H",
        "T": "C",
        "S": "C",
        "-": "C",
        "=": "=",
    },
)
# TODO: should that be residue setting?

# pylint: enable=no-member
